apiVersion: v1
kind: Pod
metadata:
  name: pgvector-pod
spec:
  containers:
    - name: pgvector
      image: pgvector/pgvector:pg18-trixie
      ports:
        - containerPort: 5432
          hostPort: 5432
      env:
        - name: POSTGRES_USER
          value: langchain
        - name: POSTGRES_PASSWORD
          value: langchain!
        - name: POSTGRES_DB
          value: cs4603_vectordb
      volumeMounts:
        - mountPath: /var/lib/postgresql
          name: pgdata
  volumes:
    - name: pgdata
      hostPath:
        path: pgvector-setup\pgdata
        type: DirectoryOrCreate
